name: Build Mecanografico

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      # 1. Descarga el codigo del repositorio
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      # 2. Instala Java 17
      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Compila el proyecto con Maven
      - name: Compilar con Maven
        run: mvn package

      # 4. Genera el instalador con jpackage (Windows)
      - name: jpackage Windows
        if: runner.os == 'Windows'
        run: |
            jpackage --input target --name Mecanografico --main-jar meca-1.0-SNAPSHOT.jar --main-class com.meca.Main --type msi --app-version 1.0 --win-console --win-menu --win-menu-group Mecanografico --win-shortcut --icon favicon.ico --dest instalador

      # 5. Genera el instalador con jpackage (Mac)
      - name: jpackage Mac
        if: runner.os == 'macOS'
        run: |
            jpackage --input target --name Mecanografico --main-jar meca-1.0-SNAPSHOT.jar --main-class com.meca.Main --type dmg --app-version 1.0 --icon favicon.icns --dest instalador

      # 6. Genera el instalador con jpackage (Linux)
      - name: jpackage Linux
        if: runner.os == 'Linux'
        run: |
          jpackage --input target --name Mecanografico --main-jar meca-1.0-SNAPSHOT.jar --main-class com.meca.Main --type deb --app-version 1.0 --dest instalador

      # 7. Sube el instalador generado a la release de GitHub
      - name: Subir instalador a la release
        uses: softprops/action-gh-release@v2
        with:
          files: instalador/*
